channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - tqdm=4.64.1
  - cartopy
  - pandas=1.5.0
  - seaborn=0.12.0
  - astropy=5.1
  - aesara
  - pymc=4.2.1
  - astropy-healpix=0.7
  - arviz
  - h5py
  - pytables
  - parse
  - colorcet
  - Jinja2
  - pip:
    - matplotlib==3.6
    - aesara-theano-fallback==0.1.0
    - wget==3.2
